version: '3'
services:
  frontend:
    image: localhost:5000/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    image: localhost:5000/backend
    ports:
      - "3001:3001"
    depends_on:
      - mongo
  mongo:
    image: localhost:5000/mongo
    ports:
      - "3306:3306"